PythonPackager: Work toward lucid packaging support

diff --git a/python-packager b/python-packager
--- a/python-packager
+++ b/python-packager
@@ -41,7 +41,7 @@ Examples:
 #    pkgf>>0.0.1, strictly greater than
 function check_build_deps()
 {
-	local FAILED=false
+	local FAILED="false"
 	for PACKAGE in ${DEPS[@]}
 	do
 		local VERSION=".*" # Match everything in the event no version is available, simplifies grepping below
@@ -65,17 +65,17 @@ function check_build_deps()
 
 		#Strip unecessary parts
 		local INSTALLED_VERSION="${INSTALLED_VERSION#Version: }"
-		local CORRECT_VERSION=true
+		local CORRECT_VERSION="true"
 		if [[ "$VERSION" != ".*" ]]
 		then
 			dpkg --compare-versions "$INSTALLED_VERSION" "$COMPARATOR" "$VERSION"
 			if [[ ! "$?" -eq "0" ]]
 			then
-				CORRECT_VERSION=false
+				CORRECT_VERSION="false"
 			fi
 		fi
 
-		if [[ "$returned" -ne "0" || "$CORRECT_VERSION" == false ]]
+		if [[ "$returned" -ne "0" || "$CORRECT_VERSION" == "false" ]]
 		then
 			if [[ -n "$OLD_PACKAGE" ]]
 			then
@@ -84,11 +84,11 @@ function check_build_deps()
 				echo "Missing package \"$PACKAGE\""
 			fi
 
-			FAILED=true
+			FAILED="true"
 		fi
 	done
 
-	if [[ "$FAILED" == true ]]
+	if [[ "$FAILED" == "true" ]]
 	then
 		return 1
 	else
@@ -121,6 +121,7 @@ function package() {
 	local TMP_DIR="$2"
 	local OUTPUT_DIR="$3"
 	local VERSION="$4"
+	local LUCID="$5"
 	local CURRENT_DIR="$PWD"
 
 	# Create the dsc
@@ -132,11 +133,20 @@ function package() {
 		return "$SUCCESS"
 	fi
 
+
 	# Determine the path we need to cd to
+	set -x
 	DEBIAN_PATH="${DEBIAN_PATH%.*}"
 	DEBIAN_PATH="${DEBIAN_PATH%.tar}"
 	DEBIAN_PATH=$(find "$TMP_DIR" -iname "$(basename $DEBIAN_PATH)")
 	cd "${DEBIAN_PATH}/debian"
+
+	# For Lucid we need to verify that the python dependency is set to >= 2.6 :(
+	if [[ "$LUCID" == "true" ]]
+	then
+		#echo "XS-Python-Version: all" >> control
+		sed -i '2s/^/X-Python-Version: all\n/' control
+	fi
 
 	# Modify version to match *-rdio#
 	if [[ "$VERSION" ]]
@@ -155,13 +165,89 @@ function package() {
 	fi
 
 	# Build the package
-	debuild -us -uc #--no-lintian
+	debuild -us -uc -b #--no-lintian
 	SUCCESS="$?"
 
 	if [[ "$SUCCESS" -ne 0 ]]
 	then
 		cd "$CURRENT_DIR"
 		return "$SUCCESS"
+	fi
+
+	# cd back out of "${DEBIAN_PATH}/debian"
+	cd -
+
+	# Lucid is terrible and it's version of dpkg doesn't support .xz compressed files
+	if [[ "$LUCID" == "true" ]]
+	then
+		echo "INFO: Attempting to convert data.tar.xz to a Lucid compatable format..."
+		cd "$TMP_DIR"
+		DEB=$(ls *.deb)
+		SUCCESS="$?"
+
+		if [[ "$SUCCESS" -ne 0 ]]
+		then
+			echo "ERROR: Could not find the .deb!"
+			cd "$CURRENT_DIR"
+			return "$SUCCESS"
+		fi
+
+		# Extract xz
+		ar x "$DEB" "data.tar.xz"
+		SUCCESS="$?"
+
+		if [[ "$SUCCESS" -ne 0 ]]
+		then
+			echo "ERROR: Could not extract data.tar.xz from deb!"
+			cd "$CURRENT_DIR"
+			return "$SUCCESS"
+		fi
+
+		# Create dir to untar to
+		mkdir data
+		tar xf data.tar.xz -C data
+		SUCCESS="$?"
+
+		if [[ "$SUCCESS" -ne 0 ]]
+		then
+			echo "ERROR: Could not extract files from data.tar.xz!"
+			cd "$CURRENT_DIR"
+			return "$SUCCESS"
+		fi
+
+		cd data
+		tar czf ../data.tar.gz *
+		SUCCESS="$?"
+
+		if [[ "$SUCCESS" -ne 0 ]]
+		then
+			echo "ERROR: Could not create data.tar.gz!"
+			cd "$CURRENT_DIR"
+			return "$SUCCESS"
+		fi
+
+		cd -
+		# Remove xz entry
+		ar d "$DEB" "data.tar.xz"
+		SUCCESS="$?"
+
+		if [[ "$SUCCESS" -ne 0 ]]
+		then
+			echo "ERROR: Could not delete data.tar.xz from .deb!"
+			cd "$CURRENT_DIR"
+			return "$SUCCESS"
+		fi
+
+		# Insert gz entry
+		ar r "$DEB" "data.tar.gz"
+		SUCCESS="$?"
+
+		if [[ "$SUCCESS" -ne 0 ]]
+		then
+			echo "ERROR: Could not add data.tar.gz to .deb!"
+			cd "$CURRENT_DIR"
+			return "$SUCCESS"
+		fi
 	fi
 
 	# Finally, copy the .deb to OUTPUT_DIR
@@ -190,10 +276,11 @@ function main() {
 	local ARCHIVE_PATH
 	local TMP_DIR
 	local RET
+	local LUCID="false"
 	local OUTPUT_DIR="$PWD"
-	local DELETE=true
+	local DELETE="true"
 	local VERSION
-	while getopts "d:f:o:t:V:" OPTION;
+	while getopts "d:f:o:t:V:L" OPTION;
 	do
 		case "$OPTION" in
 		d)
@@ -208,10 +295,13 @@ function main() {
 		t)
 			TMP_DIR="$OPTARG"
 			# Don't delete the tmp directory if it was user specified
-			DELETE=false
+			DELETE="false"
 		;;
 		V)
 			VERSION="$OPTARG"
+		;;
+		L)
+			LUCID="true"
 		;;
 		?)
 			echo "$USAGE"
@@ -252,11 +342,11 @@ function main() {
 			exit 1
 		fi
 
-		package "${TMP_DIR}/${ARCHIVE_PATH}" "$TMP_DIR" "$OUTPUT_DIR" "$VERSION"
+		package "${TMP_DIR}/${ARCHIVE_PATH}" "$TMP_DIR" "$OUTPUT_DIR" "$VERSION" "$LUCID"
 		RET=$?
 	elif [[ "$ARCHIVE_PATH" ]]
 	then
-		package "$ARCHIVE_PATH" "$TMP_DIR" "$OUTPUT_DIR" "$VERSION"
+		package "$ARCHIVE_PATH" "$TMP_DIR" "$OUTPUT_DIR" "$VERSION" "$LUCID"
 		RET=$?
 	fi
 
@@ -267,7 +357,7 @@ function main() {
 	fi
 
 	# Be super careful about cleaning up
-	if [[ "$DELETE" == true && "$RET" == 0 ]]
+	if [[ "$DELETE" == "true" && "$RET" == 0 ]]
 	then
 		if [[ "$TMP_DIR" && -d "$TMP_DIR" && "$TMP_DIR" != "$PWD" && "$TMP_DIR" != "$HOME" ]]
 		then
